### ISSUE TITLE
Playing and changing to new song locks the screen.(fully to black screen)

### ISSUE THREAD

**Issue by gsingh704** [4v3ngR/ytm-wrapped#5]

**Comment by 4v3ngR** [comment]
Can you provide some information?
* What version are you using?
* Does it happen in the debug build?
* What device are you using?
* What version of android is it running?
* Did you try with a different version of the app?
* Did any of them work?
* What happens when you have music.youtube.com loaded in a browser and do the same steps?

**Comment by gsingh704** [comment]
**What version are you using?**
0.1.16
  **Does it happen in the debug build?**
yes
 **What device are you using?**
Realme X7 pro , will try with samsung 
  **What version of android is it running?**
Android 11
 **Did you try with a different version of the app?**
ytm 0.1.5 doesnt do this
 **Did any of them work?**
yes , previous version worked
 **What happens when you have music.youtube.com loaded in a browser and do the same steps?**
I use a brave browser youtube music PWA and also have tried other , they work normally . Sometime take time to load if in background

**Comment by gsingh704** [comment]
On samsung this doesn't happen . But on both you can only skip (next song) only if the app is opened(foreground). Notification get the order but doesn't change the song, stop the song, no sound. Then if you open the app the action happen (also app looks like it reload)

**Comment by gsingh704** [comment]
v0.1.7 solved these issues

**Comment by 4v3ngR** [comment]
Thanks for the update. Glad 0.1.7 resolved the issues.
